### ISSUE TITLE
Wrong units in documentation

### ISSUE THREAD

**Issue by gsusmonzon** [Mrtenz/typeorm-store#17]
Hello,

the documentation (README) says that `ttl` configuration is in millisecods.
However looking at the code, it expects seconds. The undocumented `expirationInterval`  also  expects 'seconds'.

This is just to prevent others to make the mistake i did.

----

BTW: Thanks @Mrtenz for writting this!

**Comment by Mrtenz** [comment]
Sorry for the delay. Just fixed this!
