### ISSUE TITLE
Update findOne to follow typeorm changes past 0.3.0

### ISSUE THREAD

**Issue by bigplayalman** [Mrtenz/typeorm-store#20]
https://github.com/Mrtenz/typeorm-store/blob/5bc4d52e5adcb3ec51912615f78b7c0502abe38e/src/store.ts#L115

findOne({
    where: {
        id: 1,
    })

**Comment by Mrtenz** [comment]
Feel free to submit a PR for this!

**Comment by Mrtenz** [comment]
#21
